In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import time
import csv

In [3]:
df = pd.read_csv("runtime_results.csv")

In [4]:
df

      E     x                       p    e    r    i    m  e.1   n   t
0     A     m                       o    u    n    t  NaN  NaN NaN NaN
1     R     u                       n    t    i    m    e  NaN NaN NaN
2    2a    10  1.4781951904296875e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
3    2a    50  2.4080276489257812e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
4    2a   100  5.2928924560546875e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
5    2a   500   0.0005888938903808594  NaN  NaN  NaN  NaN  NaN NaN NaN
6    2a  1000   0.0010609626770019531  NaN  NaN  NaN  NaN  NaN NaN NaN
7    2a  1500   0.0017931461334228516  NaN  NaN  NaN  NaN  NaN NaN NaN
8    2a  2000   0.0025370121002197266  NaN  NaN  NaN  NaN  NaN NaN NaN
9    2a  3000    0.004335880279541016  NaN  NaN  NaN  NaN  NaN NaN NaN
10   2a  5000    0.008253812789916992  NaN  NaN  NaN  NaN  NaN NaN NaN
11   2b    10  6.9141387939453125e-06  NaN  NaN  NaN  NaN  NaN NaN NaN
12   2b    50  1.0967254638671875e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
13   2b   100  2.4080276489257812e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
14   2b   500  0.00013303756713867188  NaN  NaN  NaN  NaN  NaN NaN NaN
15   2b  1000   0.0004131793975830078  NaN  NaN  NaN  NaN  NaN NaN NaN
16   2b  1500   0.0008509159088134766  NaN  NaN  NaN  NaN  NaN NaN NaN
17   2b  2000   0.0009059906005859375  NaN  NaN  NaN  NaN  NaN NaN NaN
18   2b  3000   0.0014009475708007812  NaN  NaN  NaN  NaN  NaN NaN NaN
19   2b  5000   0.0023670196533203125  NaN  NaN  NaN  NaN  NaN NaN NaN
20  2ca    10      3.814697265625e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
21  2ca    25  0.00017380714416503906  NaN  NaN  NaN  NaN  NaN NaN NaN
22  2ca    50   0.0009760856628417969  NaN  NaN  NaN  NaN  NaN NaN NaN
23  2ca   100    0.009296894073486328  NaN  NaN  NaN  NaN  NaN NaN NaN
24  2cb    10  1.4066696166992188e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
25  2cb    25  1.9788742065429688e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
26  2cb    50   5.793571472167969e-05  NaN  NaN  NaN  NaN  NaN NaN NaN
27  2cb   100    0.000164031982421875  NaN  NaN  NaN  NaN  NaN NaN NaN